werShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Попробуйте новую кроссплатформенную оболочку PowerShell (https://aka.ms/pscore6)

(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12412] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 10, in <module>
    app.mount("/static", StaticFiles(directory="/app/static"), name="static")
                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/app/static' does not exist
INFO:     Stopping reloader process [12412]
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [19464] using WatchFiles
Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart

Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 17, in <module>
    @app.post("/upload", response_class=HTMLResponse)
     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 994, in decorator
    self.add_api_route(
    ~~~~~~~~~~~~~~~~~~^
        path,
        ^^^^^
    ...<23 lines>...
        generate_unique_id_function=generate_unique_id_function,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 933, in add_api_route
    route = route_class(
        self.prefix + path,
    ...<24 lines>...
        generate_unique_id_function=current_generate_unique_id,
    )
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 285, in get_dependant
    param_details = analyze_param(
        param_name=param_name,
    ...<2 lines>...
        is_path_param=is_path_param,
    )
    ensure_multipart_is_installed()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 115, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart

INFO:     Stopping reloader process [19464]
Collecting python-multipart
  Obtaining dependency information for python-multipart from https://files.pythonhosted.org/packages/45/58/38b5afbc1a800eeea951b9285d3912613f2603bdf897a4ab0f4bd7f405fc/python_multipart-0.0.20-py3-none-any.whl.metadata
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Installing collected packages: python-multipart
Successfully installed python-multipart-0.0.20

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> pip install python-multipart
Requirement already satisfied: python-multipart in c:\users\nikha\pycharmprojects\testtasklesta\.venv\lib\site-packages (0.0.20)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [3004] using WatchFiles
INFO:     Started server process [16444]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26189 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26189 - "GET /static/styles.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:26189 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:26193 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 21, in handle_upload
    tfidf_matrix = vectorizer.fit_transform([text])
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1376, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1282, in _count_vocab
    raise ValueError(
        "empty vocabulary; perhaps the documents only contain stop words"
    )
ValueError: empty vocabulary; perhaps the documents only contain stop words
INFO:     127.0.0.1:26209 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 19, in handle_upload
    text = (await file.read()).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
INFO:     127.0.0.1:26333 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26333 - "GET /static/styles.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:26334 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26334 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 21, in handle_upload
    tfidf_matrix = vectorizer.fit_transform([text])
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1376, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1282, in _count_vocab
    raise ValueError(
        "empty vocabulary; perhaps the documents only contain stop words"
    )
ValueError: empty vocabulary; perhaps the documents only contain stop words
WARNING:  WatchFiles detected changes in 'app\main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [16500]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26441 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26441 - "GET /static/styles.css HTTP/1.1" 304 Not Modified
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16500]
INFO:     Stopping reloader process [3004]
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [15496] using WatchFiles
INFO:     Started server process [836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26466 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26470 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26470 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26479 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26487 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26487 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26494 - "POST /upload HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [836]
INFO:     Stopping reloader process [15496]
werShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Попробуйте новую кроссплатформенную оболочку PowerShell (https://aka.ms/pscore6)

(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12412] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 10, in <module>
    app.mount("/static", StaticFiles(directory="/app/static"), name="static")
                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/app/static' does not exist
INFO:     Stopping reloader process [12412]
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [19464] using WatchFiles
Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart

Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\nikha\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 17, in <module>
    @app.post("/upload", response_class=HTMLResponse)
     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 994, in decorator
    self.add_api_route(
    ~~~~~~~~~~~~~~~~~~^
        path,
        ^^^^^
    ...<23 lines>...
        generate_unique_id_function=generate_unique_id_function,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 933, in add_api_route
    route = route_class(
        self.prefix + path,
    ...<24 lines>...
        generate_unique_id_function=current_generate_unique_id,
    )
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 285, in get_dependant
    param_details = analyze_param(
        param_name=param_name,
    ...<2 lines>...
        is_path_param=is_path_param,
    )
    ensure_multipart_is_installed()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 115, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart

INFO:     Stopping reloader process [19464]
Collecting python-multipart
  Obtaining dependency information for python-multipart from https://files.pythonhosted.org/packages/45/58/38b5afbc1a800eeea951b9285d3912613f2603bdf897a4ab0f4bd7f405fc/python_multipart-0.0.20-py3-none-any.whl.metadata
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Installing collected packages: python-multipart
Successfully installed python-multipart-0.0.20

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> pip install python-multipart
Requirement already satisfied: python-multipart in c:\users\nikha\pycharmprojects\testtasklesta\.venv\lib\site-packages (0.0.20)

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [3004] using WatchFiles
INFO:     Started server process [16444]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26189 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26189 - "GET /static/styles.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:26189 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:26193 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 21, in handle_upload
    tfidf_matrix = vectorizer.fit_transform([text])
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1376, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1282, in _count_vocab
    raise ValueError(
        "empty vocabulary; perhaps the documents only contain stop words"
    )
ValueError: empty vocabulary; perhaps the documents only contain stop words
INFO:     127.0.0.1:26209 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 19, in handle_upload
    text = (await file.read()).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
INFO:     127.0.0.1:26333 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26333 - "GET /static/styles.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:26334 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26334 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\app\main.py", line 21, in handle_upload
    tfidf_matrix = vectorizer.fit_transform([text])
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1376, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikha\PycharmProjects\TestTaskLesta\.venv\Lib\site-packages\sklearn\feature_extraction\text.py", line 1282, in _count_vocab
    raise ValueError(
        "empty vocabulary; perhaps the documents only contain stop words"
    )
ValueError: empty vocabulary; perhaps the documents only contain stop words
WARNING:  WatchFiles detected changes in 'app\main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [16500]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26441 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26441 - "GET /static/styles.css HTTP/1.1" 304 Not Modified
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16500]
INFO:     Stopping reloader process [3004]
(.venv) PS C:\Users\nikha\PycharmProjects\TestTaskLesta> uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\nikha\\PycharmProjects\\TestTaskLesta']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [15496] using WatchFiles
INFO:     Started server process [836]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:26466 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26470 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26470 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26479 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26487 - "POST /upload HTTP/1.1" 200 OK
INFO:     127.0.0.1:26487 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:26494 - "POST /upload HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [836]
INFO:     Stopping reloader process [15496]
